parameter_defaults:
  PublicVirtualFixedIPs: [{'ip_address':'10.50.0.251'}]
  CeilometerStoreEvents: true

  ControllerExtraConfig:
    ceilometer::agent::polling::manage_polling: true
    ceilometer::agent::polling::polling_interval: 60
  ComputeExtraConfig:
    ceilometer::agent::polling::manage_polling: true
    ceilometer::agent::polling::polling_interval: 60
