parameter_defaults:
  OvercloudControllerFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudCephStorageFlavor: ceph-storage
  OvercloudNetworkerFlavor: network
  OvercloudComputeHCIFlavor: osdcompute
  ControllerCount: 1
  ComputeCount: 0
  CephStorageCount: 0
  ComputeHCICount: 3
  NetworkerCount: 0
