parameter_defaults:
  OvercloudControllerFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudCephStorageFlavor: ceph-storage
  OvercloudNetworkerFlavor: network
  ControllerCount: 1
  ComputeCount: 1
  CephStorageCount: 0
  NetworkerCount: 1
